=== mityada/Vizi/meta/scripts/schema/configuration.dtd
<?xml version="1.0" encoding="WINDOWS-1251"?>

<!ENTITY % fonts "(Serif | SansSerif | Symbol | Monospaced)">
<!ENTITY % font-style "(plain | bold | italic | bolditalic)">
<!ENTITY % elements "(
    font | 
    color | 
    property | 
    message | 
    panel | 
    style | 
    button | 
    spin-panel | 
    adjustablePanel |
    styleset | 
    group | 
    choice
)">
<!ENTITY % boolean "(true | false)">

<!-- Configuration root -->
<!ELEMENT configuration (%elements;)*>
<!ATTLIST configuration
>

<!-- Font configuration -->
<!ELEMENT font EMPTY>
<!ATTLIST font
    description         CDATA                   #IMPLIED
    param               NMTOKEN                 "font"
    face                %fonts;                 #IMPLIED
    size                CDATA                   #IMPLIED
    style               %font-style;            #IMPLIED
>    

<!-- Color configuration -->
<!ELEMENT color EMPTY>
<!ATTLIST color
    description         CDATA                   #IMPLIED
    param               NMTOKEN                 #REQUIRED
    value               CDATA                   #REQUIRED
>    

<!-- Property -->
<!ELEMENT property EMPTY>
<!ATTLIST property
    description         CDATA                   #IMPLIED
    param               NMTOKEN                 #REQUIRED
    value               CDATA                   #REQUIRED
>    

<!-- Localized message -->
<!ELEMENT message EMPTY>
<!ATTLIST message
    description         CDATA                   #IMPLIED
    param               NMTOKEN                 #REQUIRED
    message-ru          CDATA                   #REQUIRED
    message-en          CDATA                   #REQUIRED
>    

<!-- Panel configuration -->
<!ELEMENT panel (font)>
<!ATTLIST panel
    description         CDATA                   #IMPLIED
    param               NMTOKEN                 #REQUIRED
    foreground          CDATA                   #REQUIRED
    background          CDATA                   #REQUIRED
>

<!-- Shape style -->
<!ELEMENT style (font?)>
<!ATTLIST style
    description         CDATA                   #IMPLIED
    param               NMTOKEN                 #IMPLIED
    text-color          CDATA                   #IMPLIED
    text-align          CDATA                   #IMPLIED
    message-align       CDATA                   #IMPLIED
    border-color        CDATA                   #IMPLIED
    border-status       %boolean;               #IMPLIED
    fill-color          CDATA                   #IMPLIED
    fill-status         %boolean;               #IMPLIED
    aspect              CDATA                   #IMPLIED
    aspect-status       %boolean;               #IMPLIED
    padding             CDATA                   #IMPLIED
>  

<!-- Button configuration -->
<!ELEMENT button EMPTY>
<!ATTLIST button
    description         CDATA                   #IMPLIED
    param               NMTOKEN                 #REQUIRED
    caption-ru          CDATA                   #REQUIRED
    caption-en          CDATA                   #REQUIRED
    hint-ru             CDATA                   #REQUIRED
    hint-en             CDATA                   #REQUIRED
    hotKey              CDATA                   #IMPLIED
>    

<!-- SpinPanel configuration -->
<!ELEMENT spin-panel (button, button)>
<!ATTLIST spin-panel
    description         CDATA                   #IMPLIED
    param               NMTOKEN                 #REQUIRED
    caption-ru          CDATA                   #REQUIRED
    caption-en          CDATA                   #REQUIRED
    hint-ru             CDATA                   #REQUIRED
    hint-en             CDATA                   #REQUIRED
    value               CDATA                   #REQUIRED
    max-value           CDATA                   #REQUIRED
    min-value           CDATA                   #REQUIRED
    step                CDATA                   #REQUIRED
>    

<!-- AdjustablePanel configuration -->
<!ELEMENT adjustablePanel (button, button)>
<!ATTLIST adjustablePanel
    description         CDATA                   #IMPLIED
    param               NMTOKEN                 #REQUIRED
    caption-ru          CDATA                   #REQUIRED
    caption-en          CDATA                   #REQUIRED
    hint-ru             CDATA                   #REQUIRED
    hint-en             CDATA                   #REQUIRED
    value               CDATA                   #REQUIRED
    maximum             CDATA                   #REQUIRED
    minimum             CDATA                   #REQUIRED
    unitIncrement       CDATA                   #REQUIRED
    blockIncrement      CDATA                   #REQUIRED
    blockInterval       CDATA                   #REQUIRED
>    

<!-- Styleset configuration -->
<!ELEMENT styleset (style*)>
<!ATTLIST styleset
    description         CDATA                   #IMPLIED
    param               NMTOKEN                 #REQUIRED
>    

<!-- Group configuration -->
<!ELEMENT group (%elements;)*>
<!ATTLIST group
    description         CDATA                   #IMPLIED
    param               NMTOKEN                 #REQUIRED
>    

<!-- Choice configuration -->
<!ELEMENT choice (message*)>
<!ATTLIST choice
    description         CDATA                   #IMPLIED
    param               NMTOKEN                 #REQUIRED
    hint-ru             CDATA                   #REQUIRED
    hint-en             CDATA                   #REQUIRED
>

=== mityada/Vizi/projects/vizi/src/ru/ifmo/vizi/base/configuration.xml
<?xml version="1.0" encoding="WINDOWS-1251"?>

<!DOCTYPE configuration PUBLIC
    "-//IFMO Vizi//Visualizer configuraion"
    "http://ips.ifmo.ru/vizi/configuration.dtd"
>

<configuration>
    <panel
        description = "Configuration of the client area"
        param       = "client"
        foreground  = "000000"
        background  = "ffffff"
    >
        <font
            description = "Font of the client area"
            face        = "Serif"
            size        = "14"
            style       = "plain"
        />
    </panel>
    <panel
        description = "Configuration of the controls pane"
        param       = "controls"
        foreground  = "000000"
        background  = "c0c0c0"
    >
        <font
            description = "Font of the controls pane"
            face        = "Serif"
            size        = "12"
            style       = "plain"
        />
    </panel>
    <panel
        description = "Configuration of the comments pane"
        param       = "comment"
        foreground  = "000000"
        background  = "c0c0c0"
    >
        <font
            description = "Font of the comments pane"
            face        = "Serif"
            size        = "12"
            style       = "plain"
        />
    </panel>
    <group
        description = "Hints configuration"
        param       = "hint"
    >
        <font
            description = "Font of hints"
            face        = "Serif"
            size        = "12"
            style       = "plain"
        />
        <font
            description = "Font of hints"
            param       = "hotKeyFont"
            face        = "Serif"
            size        = "12"
            style       = "bold"
        />
        <color
            description = "Hint foreground color"
            param       = "foreground"
            value       = "000000"
        />
        <color
            description = "HotKey hint foreground color"
            param       = "hotKeyForeground"
            value       = "7f7f7f"
        />
        <color
            description = "Hint background color"
            param       = "background"
            value       = "ffffe0"
        />
        <property
            description = "Vertical gap between text and border"
            param       = "vgap"
            value       = "-1"
        />
        <property
            description = "Horizontal gap between text and border"
            param       = "hgap"
            value       = "2"
        />
        <property
            description = "Delay before hint is shown"
            param       = "delay"
            value       = "1000"
        />
    </group>
    <group
        description = "Configuration of the about dialog"
        param       = "about"
    >        
        <font
            description = "Font of the legend"
            face        = "SansSerif"
            size        = "12"
            style       = "plain"
        />
        <font
            description = "Font of the legend caption"
            param       = "caption-font"
            style       = "bold"
        />
    </group>
    <group
        description = "Buttons configuration"
        param       = "button"
    >
        <button
            description = "Next-button"
            param       = "next"
            caption-ru  = ">>"
            caption-en  = ">>"
            hint-ru     = "Шаг вперед"
            hint-en     = "Step forward"
            hotKey      = "\u2192"
        />
        <button
            description = "Previous-button"
            param       = "prev"
            caption-ru  = "&lt;&lt;"
            caption-en  = "&lt;&lt;"
            hint-ru     = "Шаг назад"
            hint-en     = "Step backward"
            hotKey      = "\u2190"
        />
        <button
            description = "Next-big-button"
            param       = "next-big"
            caption-ru  = ">>>"
            caption-en  = ">>>"
            hint-ru     = "Большой шаг вперед"
            hint-en     = "Big step forward"
            hotKey      = "Shift + \u2192"
        />
        <button
            description = "Previous-big-button"
            param       = "prev-big"
            caption-ru  = "&lt;&lt;&lt;"
            caption-en  = "&lt;&lt;&lt;"
            hint-ru     = "Большой шаг назад"
            hint-en     = "Big step backward"
            hotKey      = "Shift + \u2190"
        />
        <button
            description = "'Restart' button"
            param       = "restart"
            caption-ru  = "Рестарт"
            caption-en  = "Restart"
            hint-ru     = "Начать заново"
            hint-en     = "Restart from very beginning"
            hotKey      = "Ctrl + F9"
        />
        <button
            description = "'Auto' button"
            param       = "auto"
            caption-ru  = "Авто"
            caption-en  = "Auto"
            hint-ru     = "Переключиться в\nавтоматический режим"
            hint-en     = "Switch to automatic mode"
            hotKey      = "F9"
        />
        <button
            description = "'Stop' button"
            param       = "stop"
            caption-ru  = "Стоп"
            caption-en  = "Stop"
            hint-ru     = "Переключиться в\nпошаговый режим"
            hint-en     = "Switch to manual mode"
            hotKey      = "F9"
        />
        <button
            description = "'About' button"
            param       = "about"
            caption-ru  = "?"
            caption-en  = "?"
            hint-ru     = "О визуализаторе"
            hint-en     = "About"
            hotKey      = "F1"
        />
        <button
            description = "'Save/Load' button"
            param       = "SaveLoad"
            caption-ru  = "Сохранить/Загрузить"
            caption-en  = "Save/Load"
            hint-ru     = "Сохранить/Загрузить состояние визуализатора"
            hint-en     = "Save/Load visualizer state"
        />
        <property
            description = "Whether to show save/load button"
            param       = "ShowSaveLoad"
            value       = "true"
        />
    </group>

    <adjustablePanel
        description     = "Delay tuning panel"
        param           = "delay"
        caption-ru      = "Задержка: {0,number,####}"
        caption-en      = "Delay: {0,number,####}"
        hint-ru         = "Задержка между шагами\nв автоматическом режиме"
        hint-en         = "Delay between steps\nin automated mode"
        value           = "1000"
        minimum         = "100"
        maximum         = "5000"
        unitIncrement   = "100"
        blockIncrement  = "300"
        blockInterval   = "500"
    >
        <button
            description = "Button for decreasing delay"
            param       = "decrementButton"
            caption-ru  = "&lt;&lt;"
            caption-en  = "&lt;&lt;"
            hint-ru     = "Уменьшить задержку"
            hint-en     = "Decrease delay"
        />
        <button
            description = "Button for increasing delay"
            param       = "incrementButton"
            caption-ru  = "&gt;&gt;"
            caption-en  = "&gt;&gt;"
            hint-ru     = "Увеличить задержку"
            hint-en     = "Increase delay"
        />
    </adjustablePanel>
    <group 
        description = "'About' dialog configuration"
        param       = "about" 
    >
        <button
            description = "'OK' button"
            param       = "button-ok"
            caption-ru  = "OK"
            caption-en  = "OK"
            hint-ru     = "Закрыть это окно"
            hint-en     = "Close this window"
        />
        <message
            description = "Dialog title"
            param       = "title"
            message-ru  = "О визуализаторе"
            message-en  = "About this visualizer"
        />
        <message
            description = "'Algorithm' section caption"
            param       = "algorithm-caption"
            message-ru  = "Алгоритм"
            message-en  = "Algorithm"
        />
        <message
            description = "'Author' section caption"
            param       = "author-caption"
            message-ru  = "Автор визуализатора"
            message-en  = "Author"
        />
        <message
            description = "'Supervisor' section caption"
            param       = "supervisor-caption"
            message-ru  = "Руководитель"
            message-en  = "Supervisor"
        />
        <message
            description = "'Technology' section caption"
            param       = "technology-caption"
            message-ru  = "Технология визуализации"
            message-en  = "Visualization technology"
        />
        <message
            description = "Georgiy Korneev"
            param       = "technology"
            message-ru  = "Георгий Корнеев"
            message-en  = "Georgiy Korneev"
        />
        <property
            description = "E-mail of Georgiy Korneev"
            param       = "technology-email"
            value       = "kgeorgiy@rain.ifmo.ru"
        />
    </group>

    <group
        description = "Save/Load dialog configuration"
        param       = "SaveLoadDialog"
    >
        <font
            description = "Font of the save/load dialog"
            face        = "SansSerif"
            size        = "12"
            style       = "plain"
        />
        <font
            description = "Font of the text area in the save dialog"
            param       = "text-font"
            style       = "bold"
        />
        <button
            description = "The button that is used for loading input data"
            param       = "load"
